# Generated by Django 6.0.1 on 2026-04-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_permissions_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name_en',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
