# Generated by Django 6.0.1 on 2026-04-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_advanced_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRequest',
        ),
    ]
