# Generated by Django 6.0.1 on 2026-04-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_delete_reviewrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioningredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
